# Generated by Django 5.0.1 on 2024-02-10 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 10, 32, 48, 652646, tzinfo=datetime.timezone.utc)),
        ),
    ]
